[package]
name = "adventofcode2021"
version = "0.1.0"
authors = ["coder"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
parse-display = "0.5.3"
regex = "1.4.2"
simple-error = "0.2.3"
